version: '3'
services:
        web:
                image: flask_anjl2_v1
                build: .
                ports:
                        - "8731:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
